version: "3.9"

services:
  db:
    image: postgres:12.7
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:6.2
    hostname: redis_db
    restart: always
    depends_on:
      - db

  celery:
    build: .
    image: celery:5.1
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    image: celery-beat:2.2.0
    volumes:
      - .:/code
    command: celery -A config beat -l info
    depends_on:
      - db
      - redis
